// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFRmHoZclis_ubI8AA_UNJU_76JpBDNDA',
    appId: '1:892497913052:web:a48a197587c73d8b108019',
    messagingSenderId: '892497913052',
    projectId: 'bingo-f5e3a',
    authDomain: 'bingo-f5e3a.firebaseapp.com',
    storageBucket: 'bingo-f5e3a.appspot.com',
    measurementId: 'G-MC61WWLDEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK7PLuhUw1VdNEku5lUtOdt3O5_kHN8A0',
    appId: '1:892497913052:android:58d0e2d7bd82c1e5108019',
    messagingSenderId: '892497913052',
    projectId: 'bingo-f5e3a',
    storageBucket: 'bingo-f5e3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxaJJ9qGHYJAiyXQz5B2nkaTBdZXXjtuE',
    appId: '1:892497913052:ios:a7b8b39d95f1b5f5108019',
    messagingSenderId: '892497913052',
    projectId: 'bingo-f5e3a',
    storageBucket: 'bingo-f5e3a.appspot.com',
    iosClientId: '892497913052-0j9k3s6lmbks7fc93ovavliatgb9ctjl.apps.googleusercontent.com',
    iosBundleId: 'com.mstech.bingo',
  );
}
